### PR TITLE
Update to use phoenix_live_view 0.20

### PR DESCRIPTION
**Pull request by tapickell**
This is something we ran into when needing to upgrade our application to use the latest LiveView.
All of our Icons work fine.

### CODE REVIEW

**Comment by mveytsman** [comment]
@tapickell what was the issue you had before? It looks like `>= 0.18.2` should still support `0.20.0` but this requirement would make it incompatible with older versions of liveview.

**Comment by tapickell** [comment]
> @tapickell what was the issue you had before? It looks like `>= 0.18.2` should still support `0.20.0` but this requirement would make it incompatible with older versions of liveview.

@mveytsman the `>= 0.18.2` unfortunately did not allow for Liveview `0.20.0` and caused an issue with the dependencies.
```
❯ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.248s
Because the lock depends on heroicons 0.5.2 which depends on phoenix_live_view ~> 0.18.2, the lock requires phoenix_live_view ~> 0.18.2.
And because your app depends on the lock, phoenix_live_view ~> 0.18.2 is required.
So, because your app depends on phoenix_live_view ~> 0.20.2, version solving failed.
** (Mix) Hex dependency resolution failed
```
I would not want to introduce a change that would block backwards compatibility with older versions.
We are now using our fork to be able to upgrade to LIveview `0.20.0` 
If there is a different change that would be better or if there is something maybe I missed that would allow the `0.20.0` update without changing anything here I am all ears.
Thank you.

**Comment by mveytsman** [comment]
Hey Todd no need to close this, will look into it today or tomorrow!

**Comment by mveytsman** [comment]
@tapickell as you may have found,`0.5.3` is compatible with phoenix `0.20.0` without losing backwards compatibility. See https://github.com/mveytsman/heroicons_elixir/commit/13fe5eb37d5a78dc2b001c8a8f192bbe1ef47666
 
I can confirm, as I just bumped my current app [here](https://github.com/bikebrigade/dispatch/pull/246/commits/543a384881f90e5f4e089a016801c50a821e3732) and am getting no errors. Hope that fixed it for you!

**Pull request closed without merging**
