### PR TITLE
Add update task and generate optimized version of icons

### PR DESCRIPTION
**Pull request by greven**
Related issue: https://github.com/mveytsman/heroicons_elixir/issues/6

This PR adds a mix update task so we can download new version of the icons (this is based on https://github.com/phoenixframework/tailwind) without manually downloading said files.

The update downloads the version set in the Application configuration or defaults to the latest version set in the module.
The SVGs used are the optimized, reducing the size of the inlined SVGs.

This PR also re-generated the Phoenix Components using the optimized SVGs.

### CODE REVIEW

**Comment by greven** [comment]
Looks like there is a more recent tag, missed that, so updating to the latest, will push soon.

**Comment by greven** [comment]
Hey, the tests are failing, I think the reason is because the aria-hidden is being added and on the optimized versions is already there, so it's being duplicated, I think.

**Comment by greven** [comment]
I've changed the svg_options as the attributes being repeated broke the tests.
Tests passing now.
Don't know if there is any side-effect to this? @mveytsman

**Comment by mveytsman** [comment]
@greven this looks great thank you!

I didn't realize they packaged the optimized versions - this means we can cut out the Saxy parser and all the svg_opts stuff, since that's just repeating what they did to optimize them!

My one concern is that since all the code is pre-generated  what version you have in the config wouldn't actually change anything since the user isn't generating the code

If we want the version to be user configurable we may need to go back to generating the code at compile-time instead of pregenerating and inlining the SVGs. I'm worried about slower compile times, and minimizing disk IO, but this makes me think we may want to just cache in ETS...

**Comment by greven** [comment]
Hey, thanks for the response.

Agree with that, I also mentioned that in the original issue, regarding compile-time generation.
So, for now should I remove the config part since like you say it's not doing anything basically.

Are you happy with the rest of the PR? 
If you want I can see into removing Saxy and adjusting accordingly, I've checked and the optimized version of the icons is smaller than the one created using Saxy, I guess they use [SVGO ](https://github.com/svg/svgo) or something for the original icons.

**Comment by mveytsman** [comment]
@greven I made a PR against your branch here that goes back to generation but doesn't read in all the icons on compile-tim. What do you think? https://github.com/greven/heroicons_elixir/pull/1

**Comment by mveytsman** [comment]
```
Error trying to dermine erlang version enoent
Operating System: macOS
CPU Information: Apple M1 Pro
Number of Available Cores: 10
Available memory: 16 GB
Elixir 1.13.4
Erlang ok

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
parallel: 1
inputs: none specified
Estimated total run time: 42 s

Benchmarking icon_body_cached...
Benchmarking icon_body_file...
Benchmarking icon_body_hardcoded...

Name                          ips        average  deviation         median         99th %
icon_body_hardcoded        3.47 M      288.42 ns ±12919.82%         166 ns         333 ns
icon_body_cached           2.65 M      376.88 ns ±10199.37%         291 ns         458 ns
icon_body_file           0.0450 M    22202.29 ns    ±33.62%       20958 ns       38875 ns

Comparison: 
icon_body_hardcoded        3.47 M
icon_body_cached           2.65 M - 1.31x slower +88.47 ns
icon_body_file           0.0450 M - 76.98x slower +21913.87 ns

Memory usage statistics:

Name                   Memory usage
icon_body_hardcoded           528 B
icon_body_cached              664 B - 1.26x memory usage +136 B
icon_body_file                952 B - 1.80x memory usage +424 B

**All measurements for memory usage were the same**
```

I ran a benchmark on my computer comparing hardcoding the icon to an ETS table to reading it from the file.

**Pull request merged**
