### PR TITLE
update icons

### PR DESCRIPTION
**Pull request by quentin-bettoum**
The icons have been updated on Heroicons.
They added aria-hidden="true" + 8 new icons.

### CODE REVIEW

**Comment by mveytsman** [comment]
Thank you @quentin-bettoum ❤️ 

I'll cut a new release with these. We're also tracking automating these upgrades here: https://github.com/mveytsman/heroicons_elixir/issues/6

**Comment by mveytsman** [comment]
@quentin-bettoum do you mind fixing the tests before I merge this https://github.com/mveytsman/heroicons_elixir/runs/5277134654?check_suite_focus=true

**Comment by quentin-bettoum** [comment]
It should be good now.

**Comment by mveytsman** [comment]
[0.3.2](https://hex.pm/packages/heroicons/0.3.2) released!

**Pull request merged**
