### PR TITLE
Dynamic generation of icons

### PR DESCRIPTION
**Pull request by cichacz**
Hello,
I saw that some time ago this repository was generating icons dynamically rather than having pre-generated file with all of them. I bet there is a reason for that, but maybe it's not 😄 
I was experimenting and found out that dynamic approach results in the same WebSocket message length when for example changing icon from one to another.
By generating those icons during compilation we can actually define which version to fetch and which repository to use. This will make sure users can stay up to date without action of library maintainers.

Let me know what do you think about this solution, I'll be more than happy to learn why current approach is better :)

PS. @chrismccord your book "Metaprogramming Elixir" actually inspired me to check how this library work. I was really surprised when I saw that you didn't use such approach like compile-time HTTP calls here.

### CODE REVIEW

**Comment by chrismccord** [comment]
Compile time was my main concern with the dynamic function generation, which was taking 10-12 seconds for me, vs 1s with the pre-generated approach.

**Comment by cichacz** [comment]
Hmm can you check it with my code? Maybe it’s not 1s but definitely not 10 😅 at least on M1 Mac.
Icons package is like 500 kb so I believe network conditions can be ignored when assessing…

**Comment by chrismccord** [comment]
This PR is super neat, but keep in mind we ship heroicons by default for new phoenix projects, so it needs to be necessarily light weight. This would impose two additional transitive dependencies as well as an extra HTTP coupled part of building/deploying applications, so it's cost is pretty high in that context.

**Comment by cichacz** [comment]
Those are pretty common libs but I understand your point. I was mainly thinking about easy version management using config instead of relying on bundled stuff.

**Comment by cichacz** [comment]
So I got rid of extra deps, except Jason which can be swapped for any other compatible library which Phoenix requires anyway. Also added fallback if network fails it will be built from bundled version :) 
That I suppose is the closest I could come to "necessarily light weight" and "configurable" at the same time. 
Compilation time is the same when using bundled archive, and a bit longer when downloading latest one :)

That would be it from my side, if you're still not convinced feel free to close this PR.
Thanks!

**Pull request closed without merging**
